version: '3.4'

services:
  app:
    build:
          context: .
          dockerfile: Development.Dockerfile
          target: videoindexer-azfunctions-builder
    image: videoindexer-azfunctions-prodbuild