# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Build_Cosmos_DB_Function_App
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: azure-pipelines-function-build.yml
      parameters:
        functionName: cosmo-azfunctions

- job: Build_Video_Indexer_Function_App
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: azure-pipelines-function-build.yml
      parameters:
        functionName: videoindexer-azfunctions