# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'azfunc/docker-compose.production-build.yml'
    action: 'Build Services'
    currentWorkingDirectory: '$(System.DefaultWorkingDirectory)/azfunc'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      id=$(docker create azfunc_prod:latest)
      docker cp ${id}:/home/site/wwwroot $(Build.BinariesDirectory)/azfunc
      docker rm -v $id
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/azfunc'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/azfunc_$(Build.BuildNumber).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
