# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Build_FunctionApp
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: azure-pipelines-function-build.yml
      parameters:
        functionName: functionapp

- job: Build_FrontendApp
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'frontend'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'frontend'
      customCommand: 'run build'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'frontend'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      replaceExistingArchive: true
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'webapp'
      publishLocation: 'Container'

- job: Collect_DeployScripts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: CopyFiles@2
    inputs:
      Contents: 'azuredeploy**.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'deployments'
      publishLocation: 'Container'
