version: '3.4'

services:
  app:
    build:
          context: .
          dockerfile: Development.Dockerfile
          target: cosmo-azfunctions-development
    image: cosmo-azfunctions_development
    volumes:
    - ./:/azfunc
    ports: 
      - "7072:7071" 